package com.divinelink.core.testing.factories.json.jellyseerr.model

object MediaInfoRequestResponseJson {

  val together = """
    {
      "id": 800,
      "status": 2,
      "createdAt": "2025-09-20T10:55:03.000Z",
      "updatedAt": "2025-09-20T10:55:03.000Z",
      "type": "movie",
      "is4k": false,
      "serverId": null,
      "profileId": null,
      "rootFolder": null,
      "languageProfileId": null,
      "tags": null,
      "isAutoRequest": false,
      "requestedBy": {
        "permissions": 269517880,
        "warnings": [],
        "id": 6,
        "email": "local@admin.me",
        "plexUsername": null,
        "jellyfinUsername": null,
        "username": "ScenePeek",
        "recoveryLinkExpirationDate": null,
        "userType": 2,
        "plexId": null,
        "jellyfinUserId": null,
        "avatar": "e61c8f47da45062?default=mm&size=200",
        "avatarETag": null,
        "avatarVersion": null,
        "movieQuotaLimit": null,
        "movieQuotaDays": null,
        "tvQuotaLimit": null,
        "tvQuotaDays": null,
        "createdAt": "2024-06-25T11:00:17.000Z",
        "updatedAt": "2025-06-25T13:44:35.000Z",
        "settings": {
          "id": 1,
          "locale": "",
          "discoverRegion": null,
          "streamingRegion": null,
          "originalLanguage": null,
          "pgpKey": null,
          "discordId": "",
          "pushbulletAccessToken": null,
          "pushoverApplicationToken": null,
          "pushoverUserKey": null,
          "pushoverSound": null,
          "telegramChatId": null,
          "telegramMessageThreadId": null,
          "telegramSendSilently": null,
          "watchlistSyncMovies": null,
          "watchlistSyncTv": null,
          "notificationTypes": {
            "email": 8190,
            "discord": 0,
            "pushbullet": 0,
            "pushover": 0,
            "slack": 0,
            "telegram": 0,
            "webhook": 0,
            "webpush": 8190
          }
        },
        "requestCount": 16,
        "displayName": "ScenePeek"
      },
      "modifiedBy": {
        "permissions": 269517880,
        "warnings": [],
        "id": 6,
        "email": "local@admin.me",
        "plexUsername": null,
        "jellyfinUsername": null,
        "username": "ScenePeek",
        "recoveryLinkExpirationDate": null,
        "userType": 2,
        "plexId": null,
        "jellyfinUserId": null,
        "avatar": "e61c8f47da45062?default=mm&size=200",
        "avatarETag": null,
        "avatarVersion": null,
        "movieQuotaLimit": null,
        "movieQuotaDays": null,
        "tvQuotaLimit": null,
        "tvQuotaDays": null,
        "createdAt": "2024-06-25T11:00:17.000Z",
        "updatedAt": "2025-06-25T13:44:35.000Z",
        "settings": {
          "id": 1,
          "locale": "",
          "discoverRegion": null,
          "streamingRegion": null,
          "originalLanguage": null,
          "pgpKey": null,
          "discordId": "",
          "pushbulletAccessToken": null,
          "pushoverApplicationToken": null,
          "pushoverUserKey": null,
          "pushoverSound": null,
          "telegramChatId": null,
          "telegramMessageThreadId": null,
          "telegramSendSilently": null,
          "watchlistSyncMovies": null,
          "watchlistSyncTv": null,
          "notificationTypes": {
            "email": 8190,
            "discord": 0,
            "pushbullet": 0,
            "pushover": 0,
            "slack": 0,
            "telegram": 0,
            "webhook": 0,
            "webpush": 8190
          }
        },
        "requestCount": 16,
        "displayName": "ScenePeek"
      },
      "media": {
        "downloadStatus": [],
        "downloadStatus4k": [],
        "id": 677,
        "mediaType": "movie",
        "tmdbId": 1242011,
        "tvdbId": null,
        "imdbId": null,
        "status": 2,
        "status4k": 1,
        "createdAt": "2025-09-20T10:55:03.000Z",
        "updatedAt": "2025-09-20T10:55:03.000Z",
        "lastSeasonChange": "2025-09-20T10:55:03.000Z",
        "mediaAddedAt": "2025-09-20T10:55:03.000Z",
        "serviceId": null,
        "serviceId4k": null,
        "externalServiceId": null,
        "externalServiceId4k": null,
        "externalServiceSlug": null,
        "externalServiceSlug4k": null,
        "ratingKey": null,
        "ratingKey4k": null,
        "jellyfinMediaId": null,
        "jellyfinMediaId4k": null,
        "seasons": []
      },
      "seasons": [],
      "seasonCount": 0
    }
  """.trimIndent()
}
