---
title: Details/root Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
details/root(["RootGraph"]) -- "start" --- details/media_details(["MediaDetailsGraph"])
details/root(["RootGraph"]) --- details/person(["PersonGraph"])
details/media_details(["MediaDetailsGraph"]) -- "start" --- details/details_screen("DetailsScreen")
details/person(["PersonGraph"]) -- "start" --- details/person_screen("PersonScreen")


classDef destination fill:#5383EC,stroke:#ffffff;
class details/details_screen,details/person_screen destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class details/media_details,details/person,details/root,details/media_details,details/person navgraph;
