---
title: Settings/root Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
settings/root(["RootGraph"]) -- "start" --- settings/settings(["SettingsGraph"])
settings/settings(["SettingsGraph"]) -- "start" --- settings/settings_screen("SettingsScreen")
settings/settings(["SettingsGraph"]) --- settings/account_settings_screen("AccountSettingsScreen")
settings/settings(["SettingsGraph"]) --- settings/jellyseerr_initial_content("JellyseerrInitialContent")
settings/settings(["SettingsGraph"]) --- settings/jellyseerr_settings_screen("JellyseerrSettingsScreen")
settings/settings(["SettingsGraph"]) --- settings/appearance_settings_screen("AppearanceSettingsScreen")
settings/settings(["SettingsGraph"]) --- settings/help_settings_screen("HelpSettingsScreen")
settings/settings(["SettingsGraph"]) --- settings/login_web_view_screen("LoginWebViewScreen")


classDef destination fill:#5383EC,stroke:#ffffff;
class settings/settings_screen,settings/account_settings_screen,settings/jellyseerr_initial_content,settings/jellyseerr_settings_screen,settings/appearance_settings_screen,settings/help_settings_screen,settings/login_web_view_screen destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class settings/settings,settings/root,settings/settings navgraph;
