---
title: Featurecredits/root Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
featurecredits/root(["RootGraph"]) -- "start" --- featurecredits/credits(["CreditsGraph"])
featurecredits/credits(["CreditsGraph"]) -- "start" --- featurecredits/credits_screen("CreditsScreen")


classDef destination fill:#5383EC,stroke:#ffffff;
class featurecredits/credits_screen destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class featurecredits/credits,featurecredits/root,featurecredits/credits navgraph;
